TOOLPATH = ../Tools/
INCPATH  = ../Tools/haribote/

MAKE     = $(TOOLPATH)make -r
EDIMG    = $(TOOLPATH)edimg
HARITOL  = $(TOOLPATH)haritol

default :
	$(MAKE) -C mcircle
	$(MAKE) -C calc
	$(MAKE) -C chklang
	$(MAKE) -C iview
	$(MAKE) -C invader
	$(MAKE) -C mmlplay
	$(MAKE) -C noodle
	$(MAKE) -C tview
	$(MAKE) -C type
	$(MAKE) -C osinfo
	$(MAKE) -C earnpi
	$(MAKE) -C help
	$(MAKE) -C crack
	$(MAKE) -C echo
	$(MAKE) -C launcher
	$(MAKE) -C finfo
	$(MAKE) -C osselect
	$(MAKE) -C nnall

clean :
	$(MAKE) -C mcircle	clean
	$(MAKE) -C calc		clean
	$(MAKE) -C chklang	clean
	$(MAKE) -C iview	clean
	$(MAKE) -C invader	clean
	$(MAKE) -C mmlplay	clean
	$(MAKE) -C noodle	clean
	$(MAKE) -C tview	clean
	$(MAKE) -C type		clean
	$(MAKE) -C osinfo	clean
	$(MAKE) -C earnpi	clean
	$(MAKE) -C help		clean
	$(MAKE) -C crack	clean
	$(MAKE) -C echo		clean
	$(MAKE) -C launcher	clean
	$(MAKE) -C finfo	clean
	$(MAKE) -C osselect	clean
	$(MAKE) -C nnall	clean

cleanall :
	$(MAKE) -C mcircle	cleanall
	$(MAKE) -C calc		cleanall
	$(MAKE) -C chklang	cleanall
	$(MAKE) -C iview	cleanall
	$(MAKE) -C invader	cleanall
	$(MAKE) -C mmlplay	cleanall
	$(MAKE) -C noodle	cleanall
	$(MAKE) -C tview	cleanall
	$(MAKE) -C type		cleanall
	$(MAKE) -C osinfo	cleanall
	$(MAKE) -C earnpi	cleanall
	$(MAKE) -C help		cleanall
	$(MAKE) -C crack	cleanall
	$(MAKE) -C echo		cleanall
	$(MAKE) -C launcher	cleanall
	$(MAKE) -C finfo	cleanall
	$(MAKE) -C osselect	cleanall
	$(MAKE) -C nnall	cleanall
